# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

# Uncomment when updating go.freebsd.org packages
#ignored = [
#  "go.freebsd.org/sys/vpc",
#  "go.freebsd.org/sys/vpc/vmnic",
#  "go.freebsd.org/sys/vpc/vpcp",
#  "go.freebsd.org/sys/vpc/vpcsw",
#  "go.freebsd.org/sys/vpc/vpctest",
#  "go.freebsd.org/sys/vpc/vendor/github.com/rs"
#]

[[override]]
 branch = "master"
 name = "github.com/sean-/pager"

[[override]]
 branch = "master"
 name = "github.com/rs/zerolog"

[[constraint]]
  branch = "master"
  name = "github.com/sean-/conswriter"

[[constraint]]
  branch = "master"
  name = "github.com/jackc/pgx"
